{
 "title": "Overview Profile",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Number of Applications",
   "type": "stat",
   "description": "Total number of applications in our database (each id is a individual loan application)",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT COUNT(*) FROM bankloandb.bankloan LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Funded Amount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(loan_amount) as total_funded_ammount from bankloan"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "description": "Amount that have been received back after giving the loan over entire year",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(total_payment) as total_received_amount from bankloan"
    }
   ]
  },
  {
   "title": "Average Interest Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT ROUND(AVG(int_rate) * 100, 2) FROM bankloandb.bankloan"
    }
   ]
  },
  {
   "title": "Debt to Income Ration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select round(avg(dti)*100, 5) as average_debt_to_income_ratio from bankloan\n"
    }
   ]
  },
  {
   "title": "MTD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select count(id) as total_loan_application from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (count(id) - (select count(id) as total_loan_application from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select count(id) as total_loan_application from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "Total Funded Amount ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(loan_amount) as total_funded_amount from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (sum(loan_amount) - (select sum(loan_amount) as total_funded_amount from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select sum(loan_amount) as total_funded_amount from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021\n"
    }
   ]
  },
  {
   "title": "Total Received Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(total_payment) as total_received_amount from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (sum(total_payment) - (select sum(total_payment) as total_received_amount from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select sum(total_payment) as total_received_amount from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021\n "
    }
   ]
  },
  {
   "title": "Total Funded Amount ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select round(avg(int_rate) * 100, 5) as average_interest_rate from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (round(avg(int_rate) * 100, 5) - (select round(avg(int_rate) * 100, 5) as average_interest_rate from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select round(avg(int_rate) * 100, 5) as average_interest_rate from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021\n"
    }
   ]
  },
  {
   "title": "Total Funded Amount ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select round(avg(dti)*100, 5) as average_debt_to_income_ratio from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (round(avg(dti), 5) - (select round(avg(dti), 5) as average_debt_to_income_ratio from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select round(avg(dti), 5) as average_debt_to_income_ratio from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021\n"
    }
   ]
  },
  {
   "title": "Monthly Average Interest rate",
   "type": "trend",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select month(issue_date) as month, round(avg(int_rate) * 100, 5) as average_interest_rate from bankloan group by month(issue_date) order by month(issue_date)\n"
    }
   ]
  },
  {
   "title": "Average Debt to Income Ratio",
   "type": "trend",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select\n   month(issue_date) as month,\n   round(avg(dti), 5) as average_debt_to_income_ratio\nfrom bankloan\ngroup by month(issue_date)\norder by month(issue_date)"
    }
   ]
  },
  {
   "title": "Total Loan Applications",
   "type": "trend",
   "description": "This Shows the Trend of the number of people applying for loans",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT \n   MONTH(issue_date) AS month,\n   MONTHNAME(issue_date) AS month_name, \n   COUNT(id) AS total_loan_applications\nFROM bankloan\nGROUP BY MONTH(issue_date), MONTHNAME(issue_date)\nORDER BY MONTH(issue_date)\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT \n   address_state,\n   COUNT(id) AS total_loan_applications\nFROM bankloan\nGROUP BY address_state\n"
    }
   ]
  },
  {
   "title": "Loan Applied Based on Term",
   "type": "piechart",
   "description": "Number of people categorized based on time period of the loan",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT term, COUNT(*) AS count\nFROM bankloandb.bankloan\nGROUP BY term;"
    }
   ]
  },
  {
   "title": "Purpose OfLoan",
   "type": "piechart",
   "description": "Loan applications categorized based on purpose of category by each individual.",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT purpose, COUNT(*) AS count\nFROM bankloandb.bankloan\nGROUP BY purpose;"
    }
   ]
  },
  {
   "title": "Working People",
   "type": "piechart",
   "description": "Number of people categorized based on how much time they were in the job market i.e the earning folks",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT emp_length, COUNT(*) AS count\nFROM bankloandb.bankloan\nGROUP BY emp_length;"
    }
   ]
  },
  {
   "title": "Good Loan Applicants",
   "type": "stat",
   "description": "Number of people who have take good loans that is their current loan status is either fully paid or else they are paying regularly",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select count(case when loan_status = \"Fully Paid\" or loan_status = \"Current\" then id end) as good_loan_application from bankloan"
    }
   ]
  },
  {
   "title": "Good and Bad Loan",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 11, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (count(case when loan_status = \"Fully Paid\" or loan_status = \"Current\" then id end)*100) / count(id) as good_loan_percentage from bankloan\n"
    },
    {
     "dataset": "bankloandb",
     "rawSql": "select (count(case when loan_status = \"Charged Off\" then id end)*100) / count(id) as bad_loan_percentage from bankloan"
    }
   ]
  },
  {
   "title": "Bad Loan Applicants",
   "type": "stat",
   "description": "The amount of people who's loans has been charge off which means people who failed to pay the loans regulary",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select count(case when loan_status = \"Charged Off\" then id end) as good_loan_application from bankloan"
    }
   ]
  },
  {
   "title": "Funded Amount",
   "type": "stat",
   "description": "The amount of money that has been taken from the Bank by the people under the category of good loan ",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(case when loan_status = \"Fully Paid\" or loan_status = \"Current\" then loan_amount end) as good_loan_funded_amount from bankloan"
    }
   ]
  },
  {
   "title": "Funded Amount",
   "type": "stat",
   "description": "The amount of money that the bank has given to the people under the bad loan category",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(case when loan_status = \"Charged Off\" then loan_amount end) as good_loan_funded_amount from bankloan"
    }
   ]
  },
  {
   "title": "Received Amount",
   "type": "stat",
   "description": "The amount of money that has been paid back with the interest to the Bank from the people under the good loan category",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(case when loan_status = \"Fully Paid\" or loan_status = \"Current\" then total_payment end) as good_loan_funded_amount from bankloan"
    }
   ]
  },
  {
   "title": "Received Amount",
   "type": "stat",
   "description": "The amount of money that has been finally retrieved from the people under the bad loan category",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(case when loan_status = \"Charged Off\" then total_payment end) as good_loan_funded_amount from bankloan"
    }
   ]
  }
 ]
}